version: '3.9'

services:
  crowdsec:
    image: 'crowdsecurity/crowdsec:latest-debian'
    restart: always
    container_name: crowdsec
    environment:
      # This is the list of collections we want to install
      # https://hub.crowdsec.net/browse/#collections
      COLLECTIONS: "crowdsecurity/nginx-proxy-manager"
      TZ: "Australia/Melbourne"
    volumes:
      - ./data/acquis.yaml:/etc/crowdsec/acquis.yaml
      # NPM logs from container
      - ../npm/data/logs/:/logs/npm/
      - ./data/config/:/etc/crowdsec/
      - ./data/db/:/var/lib/crowdsec/data/
      - /var/log/journal/:/run/log/journal/
    networks:
      - npm
      - crowdsec
  metabase:
    image: 'bobblybook/metabase:latest'
    restart: always
    container_name: crowdsec-metabase
    environment:
      TZ: "Australia/Melbourne"
    volumes:
      # Crowdsec read-only database
      - ./data/db/crowdsec.db:/metabase-data/crowdsec.db
      # Local metabase db, with preconfigured dashboards
      - ./data/metabase/metabase.db.mv.db:/app/metabase.db.mv.db
    ports:
      - '3000:3000'
    networks:
      - crowdsec
    depends_on: "crowdsec"
networks:
  npm:
    external: true
  crowdsec:
